from bot import TELEGRAM_API, TELEGRAM_HASH, CHANNEL_USERNAME, BOT_TOKEN

class Config(object):
    TG_BOT_TOKEN = BOT_TOKEN
    APP_ID = TELEGRAM_API
    API_HASH = TELEGRAM_HASH
    CHANNEL_USERNAME = CHANNEL_USERNAME